info:
  title: Mihari API
  version: 0.0.1
swagger: "2.0"
produces:
  - application/json
tags:
  - name: alerts
    description: Operations about alerts
  - name: artifacts
    description: Operations about artifacts
  - name: command
    description: Operations about commands
  - name: configs
    description: Operations about configs
  - name: ip_addresses
    description: Operations about ip_addresses
  - name: sources
    description: Operations about sources
  - name: tags
    description: Operations about tags
paths:
  /api/alerts/{id}:
    delete:
      description: Delete an alert
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          type: integer
          format: int32
          required: true
      responses:
        "200":
          description: Delete an alert
          schema:
            $ref: "#/definitions/Mihari_Entities_Message"
        "404":
          description: Not found
          schema:
            $ref: "#/definitions/Mihari_Entities_Message"
      tags:
        - alerts
  /api/alerts:
    get:
      description: Search alerts
      produces:
        - application/json
      parameters:
        - in: query
          name: page
          type: integer
          format: int32
          required: false
        - in: query
          name: artifact
          type: string
          required: false
        - in: query
          name: description
          type: string
          required: false
        - in: query
          name: source
          type: string
          required: false
        - in: query
          name: tag
          type: string
          required: false
        - in: query
          name: from_at
          type: string
          format: date-time
          required: false
        - in: query
          name: fromAt
          type: string
          format: date-time
          required: false
        - in: query
          name: to_at
          type: string
          format: date-time
          required: false
        - in: query
          name: toAt
          type: string
          format: date-time
          required: false
        - in: query
          name: asn
          type: integer
          format: int32
          required: false
        - in: query
          name: dns_record
          type: string
          required: false
        - in: query
          name: dnsRecord
          type: string
          required: false
        - in: query
          name: reverse_dns_name
          type: string
          required: false
        - in: query
          name: reverseDnsName
          type: string
          required: false
      responses:
        "200":
          description: Search alerts
          schema:
            type: array
            items:
              $ref: "#/definitions/Mihari_Entities_Alert"
        "404":
          description: Not found
          schema:
            $ref: "#/definitions/Mihari_Entities_Message"
      tags:
        - alerts
  /api/artifacts/{id}:
    delete:
      description: Delete an artifact
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          type: integer
          format: int32
          required: true
      responses:
        "200":
          description: Delete an artifact
          schema:
            $ref: "#/definitions/Mihari_Entities_Message"
        "404":
          description: Not found
          schema:
            $ref: "#/definitions/Mihari_Entities_Message"
      tags:
        - artifacts
    get:
      description: Get an artifact
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          type: integer
          format: int32
          required: true
      responses:
        "200":
          description: Get an artifact
          schema:
            $ref: "#/definitions/Mihari_Entities_Artifact"
        "404":
          description: Not found
          schema:
            $ref: "#/definitions/Mihari_Entities_Message"
      tags:
        - artifacts
  /api/artifacts/{id}/enrich:
    get:
      description: Enrich an artifact
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          type: integer
          format: int32
          required: true
      responses:
        "200":
          description: Enrich an artifact
          schema:
            $ref: "#/definitions/Mihari_Entities_Message"
        "404":
          description: Not found
          schema:
            $ref: "#/definitions/Mihari_Entities_Message"
      tags:
        - artifacts
  /api/command:
    post:
      description: Run a command
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: ApiCommand
          in: body
          required: true
          schema:
            $ref: "#/definitions/postApiCommand"
      responses:
        "201":
          description: Run a command
          schema:
            $ref: "#/definitions/Mihari_Entities_CommandResult"
        "400":
          description: Bad request
          schema:
            $ref: "#/definitions/Mihari_Entities_Message"
      tags:
        - command
  /api/configs:
    get:
      description: Get configs
      produces:
        - application/json
      responses:
        "200":
          description: Get configs
          schema:
            type: array
            items:
              $ref: "#/definitions/Mihari_Entities_Config"
      tags:
        - configs
  /api/ip_addresses/{ip}:
    get:
      description: Get an IP address
      produces:
        - application/json
      parameters:
        - in: path
          name: ip
          type: string
          required: true
      responses:
        "200":
          description: Get an IP address
          schema:
            $ref: "#/definitions/Mihari_Entities_IPAddress"
        "404":
          description: Not found
          schema:
            $ref: "#/definitions/Mihari_Entities_Message"
      tags:
        - ip_addresses
  /api/sources:
    get:
      description: Get sources
      produces:
        - application/json
      responses:
        "200":
          description: Get sources
          schema:
            type: array
            items:
              $ref: "#/definitions/Mihari_Entities_Sources"
      tags:
        - sources
  /api/tags/{name}:
    delete:
      description: Delete a tag
      produces:
        - application/json
      parameters:
        - in: path
          name: name
          type: string
          required: true
      responses:
        "200":
          description: Delete a tag
          schema:
            $ref: "#/definitions/Mihari_Entities_Message"
        "404":
          description: Not found
          schema:
            $ref: "#/definitions/Mihari_Entities_Message"
      tags:
        - tags
  /api/tags:
    get:
      description: Get tags
      produces:
        - application/json
      responses:
        "200":
          description: Get tags
          schema:
            type: array
            items:
              $ref: "#/definitions/Mihari_Entities_Tags"
      tags:
        - tags
definitions:
  Mihari_Entities_Message:
    type: object
    properties:
      message:
        type: string
    description: Mihari_Entities_Message model
  Mihari_Entities_Alert:
    type: object
    properties:
      id:
        type: integer
        format: int32
      title:
        type: string
      description:
        type: string
      source:
        type: string
      createdAt:
        type: string
        format: date-time
      artifacts:
        type: array
        items:
          $ref: "#/definitions/Mihari_Entities_Artifact"
      tags:
        type: array
        items:
          $ref: "#/definitions/Mihari_Entities_Tag"
    required:
      - id
      - title
      - description
      - source
      - createdAt
    description: Mihari_Entities_Alert model
  Mihari_Entities_Artifact:
    type: object
    properties:
      id:
        type: integer
        format: int32
      data:
        type: string
      dataType:
        type: string
      source:
        type: string
      tags:
        type: array
        items:
          type: string
      autonomousSystem:
        $ref: "#/definitions/Mihari_Entities_AutonomousSystem"
      geolocation:
        $ref: "#/definitions/Mihari_Entities_Geolocation"
      whoisRecord:
        $ref: "#/definitions/Mihari_Entities_WhoisRecord"
      reverseDnsNames:
        type: array
        items:
          $ref: "#/definitions/Mihari_Entities_ReverseDnsName"
      dnsRecord:
        type: array
        items:
          $ref: "#/definitions/Mihari_Entities_DnsRecord"
    required:
      - id
      - data
      - dataType
      - source
    description: Mihari_Entities_Artifact model
  Mihari_Entities_AutonomousSystem:
    type: object
    properties:
      asn:
        type: integer
        format: int32
    required:
      - asn
  Mihari_Entities_Geolocation:
    type: object
    properties:
      country:
        type: string
      countryCode:
        type: string
    required:
      - country
      - countryCode
  Mihari_Entities_WhoisRecord:
    type: object
    properties:
      domain:
        type: string
      createdOn:
        type: string
        format: date
      updatedOn:
        type: string
        format: date
      expiresOn:
        type: string
        format: date
      registrar:
        type: object
      contacts:
        type: array
        items:
          type: object
    required:
      - domain
      - contacts
  Mihari_Entities_ReverseDnsName:
    type: object
    properties:
      name:
        type: string
    required:
      - name
  Mihari_Entities_DnsRecord:
    type: object
    properties:
      resource:
        type: string
      value:
        type: string
    required:
      - resource
      - value
  Mihari_Entities_Tag:
    type: object
    properties:
      name:
        type: string
    required:
      - name
  postApiCommand:
    type: object
    properties:
      command:
        type: string
    required:
      - command
    description: Run a command
  Mihari_Entities_CommandResult:
    type: object
    properties:
      output:
        type: string
      success:
        type: boolean
    required:
      - output
      - success
    description: Mihari_Entities_CommandResult model
  Mihari_Entities_Config:
    type: object
    properties:
      name:
        type: string
      status:
        $ref: "#/definitions/Mihari_Entities_ConfigStatus"
    required:
      - name
      - status
    description: Mihari_Entities_Config model
  Mihari_Entities_ConfigStatus:
    type: object
    properties:
      type:
        type: string
      values:
        type: array
        items:
          type: string
      isConfigured:
        type: boolean
    required:
      - type
      - values
      - isConfigured
  Mihari_Entities_IPAddress:
    type: object
    properties:
      ip:
        type: string
      countryCode:
        type: string
      hostname:
        type: string
      loc:
        type: string
      asn:
        type: integer
        format: int32
    required:
      - ip
      - countryCode
      - loc
    description: Mihari_Entities_IPAddress model
  Mihari_Entities_Sources:
    type: object
    properties:
      sources:
        type: string
    required:
      - sources
    description: Mihari_Entities_Sources model
  Mihari_Entities_Tags:
    type: object
    properties:
      tags:
        type: string
    required:
      - tags
    description: Mihari_Entities_Tags model
