info:
  title: Mihari API
  version: "1.0"

openapi: 3.0.0

paths:
  /api/alerts:
    get:
      summary: Get alerts
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 0
          required: false
        - in: query
          name: artifact
          schema:
            type: string
          required: false
        - in: query
          name: description
          schema:
            type: string
          required: false
        - in: query
          name: source
          schema:
            type: string
          required: false
        - in: query
          name: tag
          schema:
            type: string
          required: false
        - in: query
          name: title
          schema:
            type: string
          required: false
        - in: query
          name: toAt
          schema:
            type: string
          required: false
        - in: query
          name: fromAt
          schema:
            type: string
          required: false
      responses:
        "200":
          description: A list of matched alerts
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AlertSearchResults"
  /api/alerts/{id}:
    delete:
      summary: Delete an alert
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        "204":
          description: Delete an alert
  /api/tags/:
    get:
      summary: Get tags
      responses:
        "200":
          description: A list of tags
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tags"
  /api/tags/{name}:
    delete:
      summary: Delete a tag
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
      responses:
        "204":
          description: Delete a tag
  /api/sources:
    get:
      summary: Get sources
      responses:
        "200":
          description: A list of sources
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sources"
  /api/artifacts/{id}:
    delete:
      summary: Delete an artifact
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        "204":
          description: Delete an artifact
  /api/config:
    get:
      summary: Get a config
      responses:
        "200":
          description: A dictionary of configuration items
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Config"
  /api/command:
    post:
      summary: Run a command
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CommandRequest"
      responses:
        "200":
          description: A result of a command
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CommandResult"
components:
  schemas:
    Tag:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    Tags:
      type: array
      items:
        allOf:
          - $ref: "#/components/schemas/Tag"
    Sources:
      type: array
      items:
        allOf:
          - type: string
    Artifact:
      type: object
      properties:
        id:
          type: integer
        data:
          type: string
        dataType:
          type: string
        source:
          type: string
          nullable: true
    Alert:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        source:
          type: string
        createdAt:
          type: string
        tags:
          type: array
          items:
            allOf:
              - $ref: "#/components/schemas/Tag"
        artifacts:
          type: array
          items:
            allOf:
              - $ref: "#/components/schemas/Artifact"
    AlertSearchResults:
      type: object
      properties:
        alerts:
          type: array
          items:
            allOf:
              - $ref: "#/components/schemas/Alert"
        currentPage:
          type: integer
        pageSize:
          type: integer
        total:
          type: integer
    ConfigItemValue:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    ConfigItem:
      type: object
      properties:
        isConfigured:
          type: boolean
        type:
          type: string
        values:
          type: array
          items:
            allOf:
              - $ref: "#/components/schemas/ConfigItemValue"
    Config:
      type: object
      additionalProperties:
        $ref: "#/components/schemas/ConfigItem"
    CommandRequest:
      type: object
      properties:
        command:
          type: string
    CommandResult:
      type: object
      properties:
        output:
          type: string
        success:
          type: boolean
